### ISSUE TITLE
Verify event on webhooks

### ISSUE THREAD

**Issue by gaishimo** [orangesys/orangesys.srv#4]
Webhookに来たイベントのデータを直接使わずにidを使ってverifyするようにする

https://stripe.com/docs/webhooks#verifying-events

**Comment by gavinzhou** [comment]
@gaishimo 
firebase cloud functionへ移行したため、不要でしょうか？
問題がなければ、repoを廃止しようと思う

**Comment by gaishimo** [comment]
はい、廃止してしまって問題ないと思います 👍
