### ISSUE TITLE
migrate to gcloud cloud function

### ISSUE THREAD

**Issue by gavinzhou** [orangesys/orangesys.srv#9]
2月中旬、cloud function beta release
移行しよと考えてます

**Comment by gavinzhou** [comment]
cloud fuctions betaリリースした

https://github.com/firebase/functions-samples

https://medium.com/google-cloud/google-firebase-middleware-in-the-cloud-called-functions-beta-is-now-available-fe977f94c0b0#.97hmfwspj

**Comment by gaishimo** [comment]
ついに来た! 

了解です 👍

**Comment by gaishimo** [comment]
Google Cloud Function、DB更新のイベントを拾えるので、認証の心配がなくなりますね。

Stripeのクレジットカード登録や変更とかはHTTPで受けないといけませんが、それ以外(例えばプラン変更等）の場合はDBの更新をFunctionで拾う形にすれば良さそうです。

**Comment by gavinzhou** [comment]
@gaishimo 
このブランチが不要となりますかな？

**Comment by gaishimo** [comment]
そうですね。不要になりますね。
